source 'https://cdn.cocoapods.org/'

platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target 'Curiouscat' do
    podspec :path => "./../Curiouscat.podspec"
end

target 'CuriouscatSample' do
    # pod 'Curiouscat', :path => "./../"
    pod 'SnapKit'
    pod 'Alamofire'
end
